model:
  name: MoonsVAE

dataset:
  id: moons
  name: moon_vae
  n_samples: 2048

optimizer:
  name: AdamW
  lr: 1.0e-3
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false
  maximize: false
  foreach: null
  capturable: false
  differentiable: false
  fused: null

train:
  seed: 97
  train_strategy: steps
  n_epochs: 5000
  n_steps: 5000
  num_workers: 0
  train_shuffle: true
  n_warmup_steps: 0
  lr_scheduler_type: constant
  batch_size: 64
  device: cuda
  grad_clip_strategy: null
  max_grad_norm: 1.0
  max_grad_value: 1.0
  gradient_accumulation_steps: 1
  real_batch_size: 64
  save_strategy: null
  save_dir: checkpoints
  save_steps: 1000
  save_epochs: 100
  save_total_limit: 3
  eval_strategy: null
  eval_steps: 500
  eval_epochs: 1
  mixed_precision: null

log:
  log_dir: logs
  log_steps: 100
  log_epochs: 999999
  log_strategy: steps

wandb:
  reinit: true
  mode: offline
  project: test
  group: default
  entity: superposed-tree

vae:
  latent_dim: 4
  decoder_sigma: 1.0
  kl_weight: 0.01
  kl_anneal_steps: 2000
  ndim_micro_shape: 1

hydra:
  run:
    dir: .
  output_subdir: null
