[project]
name = "mlkit"
version = "0.0.1"
authors = [{ name = "zengls", email = "3186428803@qq.com" }]
description = "Python package for machine learning"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "accelerate",
    "numpy",
    "tqdm",
    "einops",
    "overrides",
    "tabulate",
    "wandb",
    "psutil",
    "exrex",
    "matplotlib",
    "hydra-core",
    "omegaconf",
    "pandas",
    "seaborn",
    "datasets",
    "peft",
    "transformers",
    "torchviz",
    "graphviz",
    "safetensors",
    "diffusers",
    "scikit-learn",
    "pillow",
]

[project.optional-dependencies]
bio = ["biotite"]
hard = ["deepspeed", "flash-attn", "bitsandbytes"]

[dependency-groups]
lint = ["ruff", "ty"]
doc = [
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
]
notebook = ["ipykernel", "ipywidgets", "nbstripout"]
dev = [
    { include-group = "lint" },
    { include-group = "doc" },
    { include-group = "notebook" },
]

[tool.uv.extra-build-dependencies]
deepspeed = [{ requirement = "torch", match-runtime = true }]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[tool.uv.extra-build-variables]
flash-attn = { FLASH_ATTENTION_SKIP_CUDA_BUILD = "TRUE" }

[project.urls]
Homepage = "https://github.com/zeroDtree/my_pkg_py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
