model:
  name: MoonsMLP

dataset:
  id: moons
  name: moon_edm

optimizer:
  name: AdamW
  lr: 1.0e-2
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false
  maximize: false
  foreach: null
  capturable: false
  differentiable: false
  fused: null

train:
  seed: 97
  train_strategy: steps
  n_epochs: 10000
  n_steps: 10000
  num_workers: 0
  train_shuffle: true
  n_warmup_steps: 0
  lr_scheduler_type: constant
  batch_size: 256
  device: cuda
  grad_clip_strategy: null
  max_grad_norm: 1.0
  max_grad_value: 1.0
  gradient_accumulation_steps: 1
  real_batch_size: 256
  save_strategy: null
  save_dir: checkpoints
  save_steps: 1000
  save_epochs: 100
  save_total_limit: 3
  eval_strategy: null
  eval_steps: 500
  eval_epochs: 1
  mixed_precision: null

log:
  log_dir: logs
  log_steps: 999999
  log_epochs: 999999
  log_strategy: null

wandb:
  reinit: true
  mode: offline
  project: test
  group: default
  entity: superposed-tree

gm:
  name: EuclideanEDMDiffuser
  n_discretization_steps: 200
  P_mean: -1.2
  P_std: 1.5
  sigma_data: 0.74
  sigma_min: 4.0e-4
  sigma_max: 160.0
  rho: 7.0
  gs: 10.0
  use_2nd_order_correction: false
  use_ode_flow: true
  use_clip: false
  clip_sample_range: 1.0
  use_dyn_thresholding: false
  dynamic_thresholding_ratio: 0.995
  sample_max_value: 1.0

hydra:
  run:
    dir: .
  output_subdir: null
